version: 2
updates:
  - package-ecosystem: "terraform"
    directory: /
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      include: scope
      prefix: "terraform"
    labels:
      - "terraform"
