name: Pre-commit CI
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Cache pre-commit environment
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-

    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: always()
      with:
        commit_message: "fix: Automated Changes by Pre-commit"
