name: Pre-commit CI

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: duyl97/terraform-toolkit:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix: Automated Changes by Pre-commit"
