name: Pre-commit CI
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4

    - name: Install Terraform-docs
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: terraform-docs/terraform-docs
        platform: linux
        arch: amd64

    - name: Install Checkov
      run: pip install checkov

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: always()
      with:
        commit_message: "fix: Automated Changes by Pre-commit"
