name: Pre-commit CI
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Set up tools
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install hello

    - name: Cache pre-commit environment
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-

    - uses: pre-commit/action@v3.0.1

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: always()
      with:
        commit_message: "fix: Automated Changes by Pre-commit"
